services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - orchestrator
      - web-frontend
    networks:
      - my-net

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    expose:
      - "5000"
    networks:
      - my-net

  web-frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - my-net

  nginx:
    image: nginx:latest
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - orchestrator
      - web-frontend
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
